Graveyard - the game where 2 necromancers battle raised dead in a graveyard until one of them can no longer move!

This is an implementation of the game [[https://en.wikipedia.org/wiki/Banqi][Banqi]] with a Halloween veneer. 
It uses the Jumping cannon rules, where the cannon must jump over 1 and only 1 piece to move or capture.
(currently using banqi role names etc, that may change)



It's currently a work in progress - but has a playable GUI.
 - note: End-game notification seems to hang on closing on windows.  OSX is fine though.

** Dependencies:
Racket - you can download [[https://download.racket-lang.org][here]]

Run the following to install library dependencies:
 - =raco pkg install memoize table-panel=
 
** To play:
 - run: =racket graveyard/gui.rkt= in this directory


** How to play:
The necromancers are presented with a graveyard full of buried corpses.
Each player then either raises a corpse, or moves/captures one of the other necromancers corpses.

The game ends when one player can no longer move or raise a new corpse.


Each corpse (except the wraith--as specified in its role section) can move one plot horizontally or vertically.
Capturing is done by moving into the plot another raised piece is in.
The hierarchy of what corpse can capture what is defined below in roles.

*** Roles
    These are ordered by precedence from least to greatest vulnerability.
**** Lich - General
     The lich can capture any unit except poltergeists as poltergeists don't have enough of a presence for the lich to control them.
     The lich is vulnerable to other liches, poltergeists, and wraiths.
**** Vampire
     The vampire is vulnerable to units above it and other vampires, and can capture units below it and other vampires
**** Zombie
     The zombie is vulnerable to units above it and other zombies, and can capture units below it and other zombies
**** Ghoul
     The ghoul is vulnerable to units above it and other ghouls, and can capture units below it and other ghouls
**** Skeleton     
     The skeleton is vulnerable to units above it and other skeletons, and can capture units below it and other skeletons
**** Wraith
     The wraith is a glass cannon, capable of capturing any unit, but capturable by any except the poltergeist.
     To give the wraith the energy it needs to move or capture, it must latch on to the essence of another creature, and move through it.
**** Poltergeist
     The poltergeist can do little more than bat objects around, but their mischievous behavior is perfectly suited for stealing and breaking a liches philactory!
     The poltergeist can only capture liches and other poltergeists, and are vulnerable to all other units
